# AlertManager Configuration for SkillSwap Backend

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@skillswap.com'
  smtp_auth_username: 'alerts@skillswap.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 2h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@skillswap.com,backend-team@skillswap.com'
        subject: '🚨 CRITICAL: SkillSwap Backend Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          
          Instance: {{ .CommonLabels.instance }}
          Job: {{ .CommonLabels.job }}
          
          Time: {{ .GroupLabels.timestamp }}
          
          Dashboard: http://grafana:3000/d/skillswap-overview
        headers:
          Priority: 'high'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#critical-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Instance:* {{ .CommonLabels.instance }}
          *Time:* {{ .GroupLabels.timestamp }}
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'backend-team@skillswap.com'
        subject: '⚠️ WARNING: SkillSwap Backend Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          
          Instance: {{ .CommonLabels.instance }}
          Job: {{ .CommonLabels.job }}
          
          Time: {{ .GroupLabels.timestamp }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#backend-alerts'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Instance:* {{ .CommonLabels.instance }}

  - name: 'info-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#backend-info'
        title: 'ℹ️ Info: {{ .GroupLabels.alertname }}'
        text: |
          *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Instance:* {{ .CommonLabels.instance }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

templates:
  - '/etc/alertmanager/templates/*.tmpl'
